### PR TITLE
Bails out of initialization when Intercom function is not available

### LINKED ISSUE #17: Intercom breaks app on brave browser due to adblock

### PR DESCRIPTION
**Pull request by essensx**
fixes https://github.com/kvendrik/intercom-react/issues/17

### CODE REVIEW

**Comment by kvendrik** [comment]
Hey @essensx! Thank you for contributing! Could you give some more insight into what this does and why it's necessary?

**Comment by essensx** [comment]
Hi @kvendrik. This basically bails out of further execution if intercom global object is unavailable. That can happen if adblock is enabled or in similar cases. For example "Brave" browser has adblock by default and it breaks the whole app

**Comment by kvendrik** [comment]
@essensx gotcha do you have more insight into why Adblock causes Intercom to not initialize?

**Comment by essensx** [comment]
Not sure, seems intercom is treated as ads and iframe get blocked from fully loading

**Comment by kvendrik** [comment]
Gotcha the thing is that an early return in this case would cause Intercom not to work right? So it would have the same outcome as loudly throwing that error. I'm wondering if we can figure out a way to make Intercom work when Adblock is enabled. Maybe a good starting point would be to see if Intercom itself is able to load when Adblock is enabled. If thats not the case this is probably an issue the Intercom team should be made aware of and potentially fix on their side first. If their library does load however its probably an issue specific to this library (maybe something to do with loading it in an iframe).

**Comment by essensx** [comment]
Well, not exactly. In my app and i believe many others, deps and app code are bundled into a single bundle. If any of the code throws an error, the app stops executing. So basically intercom is breaking my app for users which use "Brave" browser. Technically the app is unusable for them 😄 

There might also be other cases where `intercom` global fails to initialize and it will break all the same - there is no checks.

Stoping adblock from blocking intercom sounds like a solution to a different problem - breaking app is a bigger issue IMHO. Not sure how to accomplish this though, doesen't Adblock block domains, etc?

**Comment by kvendrik** [comment]
@essensx to prevent that you can use an [error boundary](https://reactjs.org/docs/error-boundaries.html). Having the library return early in this case could create a scenario where it simply doesn't work and the developer doesn't know why which is why I would prefer that approach here.

I don't think we should necessarily aim to stop Adblock from blocking Intercom as if they do that there's probably a good reason for it. I was more so thinking it might be good to first check if this error is caused by our implementation of the Intercom library or by the library itself.

If it is caused by the Intercom library I think the best solution might be to leave this as is and make the Intercom team aware of the issue. If it's caused by us we can look into how to actually resolve the issue so the library will also work for people who have Adblock enabled.

**Comment by essensx** [comment]
I do have an error boundary and try to recover my users, but it's a limbo - i do hard refresh for my user, and the intercom library gets loaded again, only to crash again and get back to error boundary.

As far as i know, intercom does track some user data, which is no different than google analytics or any other third party tracking services. When GA is blocked, data is not sent to GA. You can use the app as usual.

IMHO, the app should throw a warning at best, but not stop js execution (throws an exception), as intercom is more of a "nice to have", than a critical part of your app.

**Comment by kvendrik** [comment]
@essensx gotcha so apart from how to resolve this long term I feel like a short term solution might just be for you to catch the error in the error boundary and not do anything with it?

**Comment by essensx** [comment]
Yes, that would probably do the trick 🤔

**Comment by kvendrik** [comment]
@essensx I think that might make the most sense. I'm not sure how I feel about an early return or logging a warning when the issue the library runs into is so severe that it won't work, that should probably be a full blown error like it is now.

Think the best thing to do to actually resolve this issue would be to look into if the Intercom library itself without the wrapper triggers the same issue. If so its probably something that should potentially be fixed on their side first and if not we can look into fixing this in a way that'll make the library work for people with Adblock enabled.

**Comment by essensx** [comment]
Hmm.. Not sure if its intercom library issue, as `getIntercomFromFrame` util returns `undefined`. And this basically breaks everything (as not a function is returned as expected) 🤔

**Pull request closed without merging**
